GET http://localhost:8080/hello
Accept: application/json

###

GET http://localhost:8080/test/list
Accept: application/json

###

GET http://localhost:8082/demo/list
Accept: application/json

###

POST http://localhost:8082/demo/insert
Content-Type: application/json

{
  "id": 1,
  "username": "test"
}